### ISSUE TITLE
Incluir disciplina Estrutura de Dados

### ISSUE THREAD

**Issue by bellesamways** [bellesamways/studynotes#10]
Seguindo o modelo da estrutura do projeto, incluir as notas da disciplina de Estrutura de Dados na pasta Faculdade.

O arquivo deve estar em .md, as imagens devem estar salvas na pasta `media` para então linkar dentro do arquivo.

O link para as notas de estudo é esse: https://www.evernote.com/shard/s248/sh/7ec75218-454e-40b6-985d-13dd2b683994/a7280c190c8e6aac96370d2d4a949585

Como são aulas grandes, aceito mais de um PR pra essa issue, desde que referencie quais aulas estão sendo incluídas.

Em caso de dúvidas, pode comentar a issue que estou atenta.

**Comment by wenneton** [comment]
Oi Isabelle, tô trabalhando nessa issue aqui, vou já subir o PR :smiley:
