### ISSUE TITLE
Incluir disciplina de Processos de Desenvolvimento de Software

### ISSUE THREAD

**Issue by bellesamways** [bellesamways/studynotes#3]
Seguindo o modelo da estrutura do projeto, incluir as notas da disciplina de Processos de Desenvolvimento de Software na pasta Faculdade.

O arquivo deve estar em .md, as imagens devem estar salvas na pasta `media` para então linkar dentro do arquivo.

O link para as notas de estudo é esse: 
https://www.evernote.com/shard/s248/sh/bb8862f5-7422-475c-92aa-31f7c5e3f5f0/42a9d370e75d32d2fde175168323592d

Como são aulas grandes, aceito mais de um PR pra essa issue, desde que referencie quais aulas estão sendo incluídas.

Em caso de dúvidas, pode comentar a issue que estou atenta.

**Comment by bellesamways** [comment]
só aula 1 foi adicionada

**Comment by bellesamways** [comment]
ainda falta incluir da aula 5 em diante

**Comment by henriquenasc** [comment]
Começar a fazer a partir da aula 5.
