### ISSUE TITLE
Incluir disciplina de Tecnologia da Informação e Comunicação

### ISSUE THREAD

**Issue by bellesamways** [bellesamways/studynotes#4]
Seguindo o modelo da estrutura do projeto, incluir as notas da disciplina de Tecnologia da Informação e Comunicação na pasta Faculdade.

O arquivo deve estar em .md, as imagens devem estar salvas na pasta `media` para então linkar dentro do arquivo.

O link para as notas de estudo é esse: https://www.evernote.com/shard/s248/sh/b2d8eea2-dc58-4bc2-a562-1e34b84dbfb1/f6d9176869d529b4a62045a298e55c8f

Como são aulas grandes, aceito mais de um PR pra essa issue, desde que referencie quais aulas estão sendo incluídas.

Em caso de dúvidas, pode comentar a issue que estou atenta.

**Comment by LeonardoSSev** [comment]
Estarei fazendo as aulas dessa Issue.

**Comment by bellesamways** [comment]
beleza!!
