### ISSUE TITLE
Incluir aula 6 de Inovação Tecnológica

### ISSUE THREAD

**Issue by bellesamways** [bellesamways/studynotes#42]
Seguindo o modelo da estrutura do projeto, incluir as notas da disciplina de Inovação Tecnológica na pasta Faculdade.

O arquivo deve estar em .md, as imagens devem estar salvas na pasta media para então linkar dentro do arquivo.

O link para as notas de estudo é esse: https://1drv.ms/u/s!AiQzeYC828t3pFsSokLKIVB6k2zg?e=fOJe6N

Como são aulas grandes, aceito mais de um PR pra essa issue, desde que referencie quais aulas estão sendo incluídas.

Em caso de dúvidas, pode comentar a issue que estou atenta.

**Comment by alefjan** [comment]
Peguei e fiz essa aula aqui
