### ISSUE TITLE
Incluir disciplina Modelagem de Sistemas

### ISSUE THREAD

**Issue by bellesamways** [bellesamways/studynotes#8]
Seguindo o modelo da estrutura do projeto, incluir as notas da disciplina de Modelagem de Sistemas na pasta Faculdade.

O arquivo deve estar em .md, as imagens devem estar salvas na pasta `media` para então linkar dentro do arquivo.

O link para as notas de estudo é esse: https://www.evernote.com/shard/s248/sh/11f03499-39e7-4f11-81ea-62f15337da11/9584e92eeef8c6fb46c8c609fa47d915

Como são aulas grandes, aceito mais de um PR pra essa issue, desde que referencie quais aulas estão sendo incluídas.

Em caso de dúvidas, pode comentar a issue que estou atenta.

**Comment by czrpxr** [comment]
Na aula 5 existe uma tabela com células mescladas. Pelo que me lembro nao é possível fazer isso no markdown. Existe a possibilidade de usar html (eles conversam). É problema usar html?

**Comment by bellesamways** [comment]
pode usar html sim :D
