### ISSUE TITLE
Incluir disciplina Linguagem de Programação - Java

### ISSUE THREAD

**Issue by bellesamways** [bellesamways/studynotes#9]
Seguindo o modelo da estrutura do projeto, incluir as notas da disciplina de Linguagem de Programação - Java na pasta Faculdade.

O arquivo deve estar em .md, as imagens devem estar salvas na pasta `media` para então linkar dentro do arquivo.

O link para as notas de estudo é esse: https://www.evernote.com/shard/s248/sh/509df3c5-42b5-47d9-9bbe-7ad99af234c5/6e0a676c82466316d5081467b38ee751

Como são aulas grandes, aceito mais de um PR pra essa issue, desde que referencie quais aulas estão sendo incluídas.

Em caso de dúvidas, pode comentar a issue que estou atenta.

**Comment by Kamilahsantos** [comment]
Oi, @bellesamways posso adicionar a aula 1?

**Comment by bellesamways** [comment]
oie, pode sim! não vou dar assign na issue toda pq a galera ainda pode pegar as outras aulas hehe

**Comment by lcsdevs** [comment]
Oi @bellesamways, posso adicionar a aula 2?

**Comment by bellesamways** [comment]
opa, claro @lcsdevs :)

**Comment by bellesamways** [comment]
reabrindo porque só foi inclusa a aula 1

**Comment by Roneycacau** [comment]
Mals, primeiro PR que mando esqueci que se tiver a tag de close ele fecha a issue, acabei mandando as aulas separado, seria melhor ter mandado tudo junto?

**Comment by Roneycacau** [comment]
Agora uma dúvida sobre a aula 5. Tem uma imagem com um código de exemplo de classe abstrata e tals, legal porque tem umas marcações e tals, mas não seria melhor ter isso em código mesmo? por questão de acessibilidade e tals?

**Comment by bellesamways** [comment]
é verdade @Roneycacau 

pode transformar em código mesmo, maioria dessas imagens que coloco no resumo é porque eu tava correndo pra fazer as aulas e tava com preguiça de copiar kkkk mas pra disponibilizar mesmo, quanto mais texto melhor, fica mais acessível :D

**Comment by bellesamways** [comment]
quanto as aulas, não tem problema ter mandado separado, mesmo que feche a issue eu reabro ela se ainda tiverem aulas faltando, fica tranquilo hehe

**Comment by Roneycacau** [comment]
Blz, mandei com a imagem, vou mudar e adicionar o código. O arquivo do final sobre polimorfismo peguei o link do seu evernote mesmo ok?

**Comment by bellesamways** [comment]
tudo bem 🤗
